[build]
  command = "ng build --configuration production"
  publish = "dist/frontend"

[context.production.environment]
  URL_BASE = "https://reto-tecnico-fastify-production.up.railway.app"
  NG_APP_BASE_URL = "https://reto-tecnico-fastify-production.up.railway.app"
